/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * POptionTable.java
 *
 * Created on 3/10/2009, 7:48:59 AM
 */

package org.petah.common.option.gui;

/**
 *
 * @author Petah
 */
public class POptionTable extends javax.swing.JPanel {

    /** Creates new form POptionTable */
    public POptionTable() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        scrollPane = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lHeader = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        table.setModel(new OptionTableModel());
        scrollPane.setViewportView(table);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(scrollPane, gridBagConstraints);

        lHeader.setFont(lHeader.getFont().deriveFont(lHeader.getFont().getStyle() | java.awt.Font.BOLD, lHeader.getFont().getSize()+10));
        lHeader.setText("Options");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(3, 3, 3, 3);
        add(lHeader, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lHeader;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
